# Generated by Django 4.2 on 2023-04-18 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.URLField()),
                ('description', models.TextField()),
                ('sku', models.CharField(max_length=20)),
                ('price', models.PositiveBigIntegerField()),
                ('name', models.CharField(max_length=100)),
            ],
        ),
    ]
